import "./globals.css";

import type { Metadata } from "next";
import { Roboto, Roboto_Mono } from "next/font/google";

import InformationInput from "@/components/information-input";
import SideBar from "@/components/sidebar";

const robotoSans = Roboto({
  variable: "--font-roboto-sans",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${robotoSans.variable} ${robotoMono.variable} flex h-screen w-screen antialiased`}
      >
        <SideBar />
        <div className="bg-background flex grow flex-col px-32 py-8">
          <div className="mb-4 grow">{children}</div>

          <InformationInput />
        </div>
      </body>
    </html>
  );
}
