import "./globals.css";

import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Roboto, Roboto_Mono } from "next/font/google";

import { fetchChat } from "@/lib/data";

import SideBar from "@/components/sidebar";

const robotoSans = Roboto({
  variable: "--font-roboto-sans",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const chats = await fetchChat();

  return (
    <SessionProvider>
      <html lang="en">
        <body
          className={`${robotoSans.variable} ${robotoMono.variable} flex h-screen w-screen antialiased`}
        >
          <SideBar chats={chats} />
          <div className="bg-background flex grow flex-col px-32 py-8">
            {children}
          </div>
        </body>
      </html>
    </SessionProvider>
  );
}
